import React from "react";

const ArticleThree = () => {
	return (
		<div div className="container mx-auto mt-10 mb-5">
			<div className="lg:mx-60">
				<div className="shadow ">
					<div className=" bg-gray-100 lg:px-16 px-3  pb-10 ">
						<div className="  ">
							<h1 className="  border-t-4 border-sky-700"></h1>
							<h1 className="text-center text-2xl font-bold mb-8 mt-5">
								FUNDING SOCIAL EXPENDITURE WITH RISK SHARING SUKUK
							</h1>
							<h1 className=" font-serif text-md font-bold text-justify mt-4">
								<p>By Prof. Dr. Obiyathulla Ismath Bacha</p>
							</h1>
							<div className="text-justified">
								{" "}
								<p className=" mb-2 text-justify font-serif">
									We have already discussed how governments could fund revenue
									generating infrastructure projects using Mudarabah/Musharakah
									type sukuk. These were risk-sharing instruments that enabled
									the sharing of profits/losses between a host government and
									sukukholders. Since the returns to these instruments came from
									revenue/profits generated by the project undertaken, there was
									minimal stress on government budgets. Governments also avoided
									the leverage and potential problems that arise with debt
									financing.
								</p>
								<p className=" mb-2 text-justify font-serif">
									While the use of risk-sharing instruments for the funding of
									revenue generating infrastructure projects is easy to
									understand, one would be tempted to ask if such instruments
									could also be used for the funding of non-revenue generating
									infrastructure. The answer is, yes, it would be possible. To
									understand how, let us examine the case of a government
									seeking financing to build a network of rural roads and
									drainage system. This is obviously not a revenue generating
									project, thus the above profit and loss sharing contracts
									cannot be used. Even so, the principle of risk-sharing would
									require that the government’s repayment of the obligation
									created be linked to some proxy or indicator of government
									revenue. One such indicator is nominal GDP or Gross Domestic
									Product. GDP is a measure of a nation’s output of goods and
									services. Since government revenue comes from income, excise
									and other indirect taxes, government revenue would invariably
									be linked to economic activity or GDP growth. In addition, as
									more and more governments move towards a Goods and Services
									Tax (GST) regime, government revenue is even more closely
									aligned to GDP. In using a GDP linked sukuk to fund the
									financing of the rural roads and drainage system, the
									government sells some asset it owns, for example an office
									complex, to a Special Purpose Vehicle (SPV). The SPV which is
									managed by an independent trustee issues Sukuk Ijarah. Over
									the tenor of the sukuk, the government, since it continues to
									use the “sold” asset, makes periodic ‘lease’ or Ijarah
									payments to the SPV, which then passes it on to the
									sukukholders. At maturity, the office building is sold back to
									the government. The proceeds from this sale is used to settle
									the face-value of the sukuk.
								</p>
								<p className="mb-2  text-justify font-serif">
									The arrangement above is much safer for a government since the
									lease amounts are linked to GDP growth. When growth is faster,
									the government pays more whereas when growth is slow, the
									lease/Ijarah payments are lower. There are several benefits
									that arise from this arrangement. First, since the obligation
									is being matched to ability to pay, there is an in-built
									stabilizer. The second big benefit is the fact that a growth
									linked instrument would not necessitate pro-cyclical policies.
									Governments heavily in-debt are usually forced to cut back on
									development and social welfare expenditures during economic
									downturns because debt servicing eats away a large portion of
									their reduced revenue. By being forced to cut back on such
									social and development, two things happen. First, the downturn
									is worsened. Instead of undertaking counter-cyclical policies
									that would require a bigger outlay by the government, debt
									servicing requirements force the opposite. Second, and perhaps
									more damaging is the fact that such a cutback often hits the
									poorest segments of society the most. Inequality widens at the
									same time as a shrinking economy. Simulations have shown that
									had Mexico funded its debt with GDP linked securities, it
									would not have suffered as much as it did in 1994. The debt
									servicing requirement would have reduced by as much as 1.7% of
									GDP, a saving that could have been used for social services.
									In the event, debt servicing requirements forced Mexico to cut
									back on social services, including basic expenditure on health
									and the like. It was the hardship caused by these cutbacks
									that led to street protests and the subsequent political
									problems.
								</p>
								<p className="mb-2  text-justify font-serif">
									To holders of GDP linked sukuk, the risk is higher than
									conventional government bonds that carry fixed interest,
									however, their returns too will be higher. The higher returns,
									compensate for the higher risk they take. To governments, this
									translates into higher cost of funding relative to debt.
									However, the higher cost comes with the safety afforded by a
									flexible instrument. The cost argument here is very much like
									the cost versus risk tradeoff between debt and equity that
									corporations face.
								</p>
								<p className="mb-2 font-serif text-justify">
									Linking debt service to GDP is not exactly a new idea.
									Unfortunately, since its first use as part of the Brady Plan
									in the 1980s, and the subsequent use by the likes of Argentina
									and other highly indebted countries has meant that it has an
									image or perception problem. Yet given today’s conundrum with
									debt and the need to deleverage, GDP linked securities are
									being revisited. In the Islamic Finance space, there are
									numerous sukuk, including sovereign ones that have
									Ijarah/lease payments benchmarked on LIBOR (London Interbank
									Offer Rate). This is indeed an irony given the abhorrence for
									interest in Shariah. Replacing the benchmark to LIBOR, with a
									benchmark to nominal GDP makes eminent sense, especially from
									a Shariah viewpoint.
								</p>
							</div>
							<p className="mt-10 font-serif text-justify"></p> *This article
							first appeared in{" "}
							<a href="https://www.inceif.org/kmimpact/author/kmc/"> INCEIF</a>{" "}
							KMC on 2 April, 2020.
							<h1 className="  border-t-8 mt-3 border-sky-700"></h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
};

export default ArticleThree;
